language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
install:
  - npm install

before_script :
    - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
    - export jsonReturn=$(node ./testRunCall.js)
#env:
#  - TESTFOLDER=/home/travis/build/Fanch-/cypress_test/cypress/integration/examples
#  - TESTFOLDER=/home/travis/build/Fanch-/cypress_test/cypress/integration/examples2
script:
   - cypress run --env commit_msg=$TRAVIS_COMMIT_MSG,rapport_id=$jsonReturn
